[package]
name = "msg-extractor"
version = "0.1.0"
authors = ["lau"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ole = "0.1.15"